export const realEvents = [
  {
    convenorsShortName: 'Sociedad de Debate UCAB',
    convenorsCompleteName: 'Sociedad de Debate UCAB',
    country: 'VE',
    countryCode: 'VE',
    coverUrl: 'https://live.staticflickr.com/65535/50048891066_b5d6fbbbcb_b.jpg',
    description:
      'Torneo BP. Incluye categoría novatos. Premios de diplomados al mejor juez y al equipo campeón',
    startDate: '2020-07-10',
    endDate: '2020-07-12',
    infoLink: 'https://instagram.com/ucab_debate?igshid=v1m1bi140xkq',
    name: 'Copa Andrés Bello',
    shortName: 'Copa Andrés Bello',
    registerLink:
      'https://docs.google.com/forms/d/1PW8m7B4i7HoDeMM0ksT-8fu7cDF_zJ9t4AC2i2UPRiE/edit?chromeless=1',
    reunionSpot: 'Discord',
    tags: [
      { key: 'type', text: 'Torneo' },
      { key: 'attendanceType', text: 'Virtual' },
      { key: 'formatType', text: 'BP' },
    ],
  },
  {
    convenorsShortName: 'Círculo de debate San Marcos',
    convenorsCompleteName: 'Círculo de debate San Marcos y OdSM',
    country: 'PE',
    countryCode: 'PE',
    coverUrl: 'https://live.staticflickr.com/65535/50045728437_72b4a02ec4_b.jpg',
    description:
      'Torneo OPEN de antesala al Torneo de Novatos (ToNo). S/.5 o $2 por oradorx. Jueces no pagan. Premios en dinero para top speaker, top juezx y equipo ganador. Parte del dinero recaudado es para los premios del ToNo, que será gratuito',
    startDate: '2020-07-11',
    endDate: '2020-07-12',
    infoLink: 'https://web.facebook.com/events/559516174713615/',
    name: 'Las Previas del ToNo 2da Edición',
    shortName: 'Pre ToNo 2',
    registerLink: 'https://forms.gle/9oEtBihwmqwNY7uh8 ',
    reunionSpot: 'Discord',
    tags: [
      { key: 'type', text: 'Torneo' },
      { key: 'attendanceType', text: 'Virtual' },
      { key: 'formatType', text: 'BP' },
    ],
  },
  {
    convenorsShortName: 'USFQ',
    convenorsCompleteName: 'USFQ y CMUDE 2020',
    country: 'EC',
    countryCode: 'EC',
    coverUrl: 'https://live.staticflickr.com/65535/50020911391_502cca8ddf_c.jpg',
    description: 'Toneo Virtual de la organización de CMUDE Ecuador 2020',
    startDate: '2020-07-17',
    endDate: '2020-07-19',
    infoLink: 'https://www.facebook.com/CMUDEcuador/',
    name: 'CMUDE Trailer 2020',
    shortName: 'CMUDE Trailer 2020',
    registerLink: 'https://forms.gle/nyHo2NHgwNRt7CjJ8',
    reunionSpot: '-',
    tags: [
      { key: 'type', text: 'Torneo' },
      { key: 'attendanceType', text: 'Virtual' },
      { key: 'formatType', text: 'BP' },
    ],
  },
  {
    convenorsShortName: 'Círculo de debate San Marcos',
    convenorsCompleteName:
      'Círculo de debate San Marcos y Universidad Nacional Mayor de San Marcos',
    country: 'PE',
    countryCode: 'PE',
    coverUrl: 'https://live.staticflickr.com/65535/50045728437_72b4a02ec4_b.jpg',
    description:
      'El ToNo nace para brindar espacios a novatxs de aprendizaje y comodidad, pero no solo eso, traemos también: 9 rondas novatos, 7 rondas máster (jueces), 200 dólares en premios, inscripción gratuita, competencia de discursos virtual y novedosa, talleres, breafing de mociones',
    startDate: '2020-07-17',
    endDate: '2020-07-26',
    infoLink: 'https://www.facebook.com/ToNo.OdSM/',
    name: 'Torneo de Novatxs Intersociedades de Debate',
    shortName: 'ToNo',
    registerLink: 'https://www.facebook.com/ToNo.OdSM/',
    reunionSpot: 'Discord',
    tags: [
      { key: 'type', text: 'Torneo' },
      { key: 'attendanceType', text: 'Virtual' },
      { key: 'formatType', text: 'BP' },
    ],
  },
  {
    convenorsShortName: 'Argumentum ESPOL',
    convenorsCompleteName: 'Argumentum ESPOL',
    description:
      'Open Internacional que además cuenta con break en categoría ELE y Novatos. Además, se tendrá competencia de másters y de discursos. ',
    country: 'EC',
    countryCode: 'EC',
    coverUrl: 'https://live.staticflickr.com/65535/50021167112_36526542c9_c.jpg',
    startDate: '2020-08-08',
    endDate: '2020-08-15',
    infoLink: 'https://www.instagram.com/argumentumdigital',
    shortName: 'TIDDA 3',
    name: 'Torneo Internacional de Debate Digital Argumentum, tercera edición. ',
    registerLink: 'https://forms.gle/g3Kd4Ba9apGS6LBr9',
    reunionSpot: '-',
    tags: [
      { key: 'type', text: 'Torneo' },
      { key: 'attendanceType', text: 'Virtual' },
      { key: 'formatType', text: 'BP' },
    ],
  },

  {
    convenorsShortName: 'Sociedad de Debate USM',
    convenorsCompleteName:
      'Sociedad de Debate de la Universidad Técnica Federico Santa María',
    country: 'CL',
    countryCode: 'CL',
    coverUrl: 'https://live.staticflickr.com/65535/50042552507_3a6443c3fc_h.jpg',
    description:
      'El TorNaDO es una instancia destinada a potenciar el circuito de debate chileno',
    startDate: '2020-08-28',
    endDate: '2020-09-06',
    infoLink: 'http://www.debatiendo.cl/tornado2020.html',
    shortName: 'TorNaDO 2020',
    name: 'Torneo Nacional de Debate 2020',
    registerLink: 'http://bit.ly/tornado2020',
    reunionSpot: 'Mixidea',
    tags: [
      { key: 'type', text: 'Torneo' },
      { key: 'attendanceType', text: 'Virtual' },
      { key: 'formatType', text: 'BP' },
    ],
  },

  {
    convenorsShortName: 'Debate ESAN',
    convenorsCompleteName: 'Universidad ESAN y Debate ESAN',
    country: 'PE',
    countryCode: 'PE',
    coverUrl: 'https://live.staticflickr.com/65535/50042551952_7bd4d42c28_k.jpg',
    description:
      'El campeonato escolar más grande e importante del Perú, en formato WSDC,abre sus puertas, en su IV edición, a todos los colegios de América Latina y Centroamérica. Talleres previos y muchas sorpresas mas.',
    startDate: '2020-09-19',
    endDate: '2020-09-20',
    infoLink: 'https://www.facebook.com/DebateEsan/',
    shortName: 'Campeonato Escolar',
    name: 'Campeonato Escolar Debate ESAN',
    registerLink: 'https://www.facebook.com/DebateEsan/',
    reunionSpot: 'Discord',
    tags: [
      { key: 'type', text: 'Torneo' },
      { key: 'attendanceType', text: 'Virtual' },
      { key: 'formatType', text: 'WSDC' },
    ],
  },
];
